services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus_dev
    container_name: perpus_app
    pull_policy: never
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel-network

  db:
    image: postgres:10.23-alpine
    container_name: perpus_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: perpus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 2

volumes:
  postgres-data:

networks:
  laravel-network:
    driver: bridge
