services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus_dev
    pull_policy: never
    container_name: perpus_app
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel-network
  db:
    image: postgres
    container_name: perpus_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: perpus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

volumes:
  postgres-data:

networks:
  laravel-network:
    driver: bridge
